import type { Metadata } from "next";
import "./globals.css";
import AppShell from "@/components/AppShell";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased h-dvh overscroll-none overflow-hidden"
      >
        <Suspense fallback={<div className="h-dvh overflow-hidden" />}>
          <AppShell>{children}</AppShell>
        </Suspense>
      </body>
    </html>
  );
}
